# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "45510020c776f4d9e63fce17d2d9cf49"
name = "ad-video-generator"
handle = "ad-video-generator-1"
application_url = "https://lookmotion.ai"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_files"

[auth]
redirect_urls = ["https://lookmotion.ai/auth/callback", "https://lookmotion.ai/auth/shopify/callback", "https://lookmotion.ai/api/auth/callback"]

[pos]
embedded = false
