# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6e91edf0bcc5ba4bcd43b010c32ffd9e"
name = "ad-video-generator"
application_url = "https://lookmotion.ai"
embedded = true
handle = "ad-video-generator-2"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_files,write_products"

[auth]
redirect_urls = [
  "https://lookmotion.ai/auth/callback"
]

[pos]
embedded = false
